name: Install
on:
  workflow_dispatch:
    inputs:
      LeviLamina:
        description: 'LeviLamina version'
        required: true
        default: '0.10.2'
      LSE:
        description: 'LegacyScriptEngine version'
        required: true
        default: '0.5.2'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    - name: Check Out
      uses: actions/checkout@v4
    - name: Install LeviLamina
      run: |
        7z x -oLeviLamina 1.zip
        cd LeviLamina
        ../lip.exe install -y github.com/LiteLDev/LeviLamina@${{ github.event.inputs.LeviLamina }}
        del bedrock_server.exe.bak
        del bedrock_server_mod.exe
        del bedrock_server.pdb
    - name: Install LSE
      run: |
        cd LeviLamina
        ../lip install -y gitea.litebds.com/LiteLDev/legacy-script-engine-lua@${{ github.event.inputs.LSE }}
        ../lip install -y gitea.litebds.com/LiteLDev/legacy-script-engine-quickjs@${{ github.event.inputs.LSE }}
        ../lip install -y gitea.litebds.com/LiteLDev/legacy-script-engine-nodejs@${{ github.event.inputs.LSE }}
        ../lip install -y gitea.litebds.com/LiteLDev/legacy-script-engine-python@${{ github.event.inputs.LSE }}
        ../lip install -y github.com/LiteLDev/LegacyScriptEngine@${{ github.event.inputs.LSE }}
        cd ../
    - name: Pack files
      run: |
        cd LeviLamina
        7z a -tzip "LeviLamina-${{ github.event.inputs.LeviLamina }}-with-LSE-${{ github.event.inputs.LSE }}.zip" .\
        copy "LeviLamina-${{ github.event.inputs.LeviLamina }}-with-LSE-${{ github.event.inputs.LSE }}.zip" ..\
        del "LeviLamina-${{ github.event.inputs.LeviLamina }}-with-LSE-${{ github.event.inputs.LSE }}.zip"
        cd ..
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: "LeviLamina-${{ github.event.inputs.LeviLamina }}-with-LSE-${{ github.event.inputs.LSE }}.zip" 
        name: LeviLamina-${{ github.event.inputs.LeviLamina }}&LSE-${{ github.event.inputs.LSE }}
        tag_name: LeviLamina-${{ github.event.inputs.LeviLamina }}&LSE-${{ github.event.inputs.LSE }}
        body: |
          LeviLamina版本: ${{ github.event.inputs.LeviLamina }}
          LSE版本: ${{ github.event.inputs.LSE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
